[build]
publish = "dist"
command = "npm run build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/assets/*.mjs"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
